version: '3.8'

services:
  database:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: news_aggregator
    volumes:
      - db_data:/var/lib/mysql:rw  # Persist database data with read-write options

  news-aggregator-api:
    build:
      context: ./news-aggregator-api
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: news_aggregator
      DB_USERNAME: root
      DB_PASSWORD: 12345
      LOG_CHANNEL: stack
      APP_ENV: local
      APP_DEBUG: "false"
      JWT_TTL: 60
      JWT_SECRET: chc5wyOJNMy0ord0HNNAKoSmVMRGesGoU5ICULYKgSSM3UZjFkcn0zE57kTAo10q
      NEWS_API_KEY: c57beb35edb14567bd7c18b7dd8357f7
      GAURDIAN_NEWS_API_KEY: 5eeead5e-ded4-49e7-8055-ddb2bb1aeea6
      NYT_NEWS_API_KEY: w5TuygkfYAAwW4FvoqMsG85UPh03wFAe,
      PAGINATION_LIMIT: 9
    volumes:
      - ./news-aggregator-api:/var/www/html:rw,delegated  # Mount local directory with read-write options
    depends_on:
      - database

  news-aggregator-web:
    build:
      context: ./news-aggregator-web
    ports:
      - "3000:3000"
    depends_on:
      - news-aggregator-api

volumes:
  db_data:  # Named volume for database persistence